spring.application.name=bff-agenda

user.url=localhost:8080/users
tasks.url=localhost:8081/tasks
notification.url=localhost:8082/email

server.port=8083

cron.time=0 0/5 * * * ?
user.email=admin@admin.com
user.password=1234